name: unit-tests

on:
  push:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1

jobs:
  start-test-stop:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service:
          - bff
          - frontend
    steps:
      - uses: actions/checkout@v3
      #
      # Cache settings
      - name: cache the docker images
        uses: actions/cache@v3
        with:
          path: tmp/docker-images
          key: ${{ github.workflow }}-tmp-docker-images-${{ hashFiles('Dockerfile.d/**') }}
      - name: cache the pnpm store
        uses: actions/cache@v3
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-dotpnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: cache user deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-dotnpm-${{ hashFiles('**/package-lock.json') }}
      - name: cache workspace deps
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: cache service deps - ${{ matrix.service }}
        uses: actions/cache@v3
        with:
          path: ${{ matrix.service }}/node_modules
          key: ${{ runner.os }}-${{ matrix.service }}-node_modules-${{ hashFiles('${{ matrix.service }}/package-lock.json') }}
      #
      # Envirinment settings
      - name: Export UIDs as environment variables
        run: |
          echo "DOCKER_GID=$(getent group docker | cut -d : -f 3)" >> .env
          echo "GID=$(id -g)" >> .env
          echo "UID=$(id -u)" >> .env
      #
      # Prepare services
      - name: Load the docker image if it exists
        timeout-minutes: 4
        run: |
          docker compose --profile=dev-all config --format=json\
           | jq --compact-output --raw-output '[.services[] | select((.image != null) and (.image | startswith("local.local"))) | .image] | sort | unique | .[]'\
           | sed -e 's!^local.local/no-name/\([[:alnum:]-]\+\):HEAD$!\1!'\
           | xargs -I '{srv}' --max-procs=0 --verbose\
           bash -lc '
          \test -f tmp/docker-images/{srv}\
           && docker load --input tmp/docker-images/{srv}\
           || echo "{srv} not exists"\
          '
      - name: Pull containers - ${{ matrix.service }}
        timeout-minutes: 4
        run: |
          docker compose pull --include-deps ${{ matrix.service }}
      - name: Build containers - ${{ matrix.service }}
        timeout-minutes: 4
        run: |
          docker compose build ${{ matrix.service }}
      - name: Save the docker image
        timeout-minutes: 4
        run: |
          docker images\
           --filter=reference='local.local/no-name/*-dev'\
           --format='{{.Repository}}'\
           | sed -e 's!^local.local/no-name/!!'\
           | xargs -I '{img}' --max-procs=0 --verbose\
           docker save --output 'tmp/docker-images/{img}' 'local.local/no-name/{img}:HEAD'
      - name: Start the service - ${{ matrix.service }}
        timeout-minutes: 2
        run: |
          docker compose up --wait ${{ matrix.service }}
      - name: Wait the service - ${{ matrix.service }}
        timeout-minutes: 4
        run: |
          while :
          do
            docker compose ps --format=json ${{ matrix.service }}\
             | jq --exit-status '.[] | select(.Health=="healthy")' 2> /dev/null\
             && break
            sleep 1
          done
          docker compose logs ${{ matrix.service }}
      - name: Show logs - bff
        run: |
          docker compose logs bff
      - name: Show logs - frontend
        run: |
          docker compose logs frontend

      #
      # Test services
      - name: Test the service - ${{ matrix.service }}
        timeout-minutes: 4
        run: |
          docker compose exec ${{ matrix.service }} npm run test:ci
      - name: Lint the service - ${{ matrix.service }}
        timeout-minutes: 4
        run: |
          docker compose exec ${{ matrix.service }} npm run lint
      #
      # Clean up
      - name: Stop services
        timeout-minutes: 1
        run: |
          docker compose down
